apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: financial-services
  description: Financial Services
spec:
  type: organization
  profile:
    displayName: Financial Services
  children: [customer-finance]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: customer-finanace
  description: Customer Finance
spec:
  type: department
  profile:
    displayName: Customer Finanace
  parent: financial-services
  children: [attract, forc]
