apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: financial-services
  description: Financial Services
spec:
  type: organization
  profile:
    displayName: Financial Services
  children: [customer-finance]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: customer-finanace
  description: Customer Finance
spec:
  type: department
  profile:
    displayName: Customer Finanace
  parent: financial-services
  children: [attract, forc]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: forc
  description: Financial Orchestration
spec:
  type: team
  profile:
    displayName: Financial Orchestration
  parent: customer-finanace
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: attract
  description: Attract
spec:
  type: team
  profile:
    displayName: Attract
  parent: customer-finanace
