apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: forc-team
  description: Financial Orchestration Team
spec:
  type: team
  profile:
    displayName: Financial Orchestration Team
  parent: customer-finanace
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: attract-team
  description: Attract Team
spec:
  type: team
  profile:
    displayName: Attract Team
  parent: customer-finanace
  children: []
